apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
  namespace: {{ .Values.rootNamespace }}
  labels:
    app: {{ .Values.backend.deploymentName }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.deploymentName }}
    spec:
      containers:
        - name: {{ .Values.backend.deploymentName }}
          image: {{ .Values.backend.imageURL }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.backend.secretName }}
      {{- if .Values.backend.requiresRegistryAuth }}
      imagePullSecrets:
        - name: {{ .Values.backend.imagePullSecretName }}
      {{- end }}
