{{- if .Values.backend.mountCodeRoot }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backend.mount.pvcName }}
spec:
  storageClassName: ssd-hostpath
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: {{ .Values.backend.mount.storage }} } }
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: '{{ .Values.rootDir }}/back'
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-ssd
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
        claimName: {{ .Values.backend.mount.pvcName }}
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pvc
          mountPath: /back
{{- end }}